---
title: "Glossary"
author: ""
date: ""
output: md_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# General terms



###Cradle-to-gate
System boundary delineation from raw material extraction through to the so-called “gate” of the manufacturing facility, including upstream energy and material production, all associated transport, and on-site manufacturing.  

###Cradle-to-grave
System boundary delineation covering the entire product life cycle, from raw material extraction to end of life. This generally includes everything in the cradle-to-gate system boundaries plus the installation, use, and EoL disposition (e.g. landfill, recycling, composting, or incineration) stages of the product or system.

###Cradle-to-cradle
A system boundary delineation that is the same as cradle-to-grave, but implies a specific fate (reuse or recycling) at end of life.

###Functional unit
“Quantified performance of a product system for use as a reference unit” (ISO 14040:2006, section 3.20).

###Gate-to-grave
System boundary delineation covering one or more processes through to end of life. While the initial gate can vary, this generally includes everything after the cradle-to-gate boundary such as use, maintenance, and EoL disposition (e.g. landfill, recycling, composting, or incineration) stages of the product or system.

###Human health endpoint
Disease symptom or related marker of a health impact on a human or other being, e.g., cancer or reproductive toxicity.

###Impact assessment category
A “class representing environmental issues of concern to which life cycle inventory analysis results may be assigned.” (ISO 14040:2006, section 3.39).

###Life cycle
A holistic view of a product or system as “consecutive and interlinked stages … from raw material acquisition or generation from natural resources to final disposal” (ISO 14040:2006, section 3.1). 

###Life Cycle Assessment (LCA)
“Compilation and evaluation of the inputs, outputs and the potential environmental impacts of a product system throughout its life cycle” (ISO 14040:2006, section 3.2).

###Life Cycle Inventory (LCI)
“Phase of life cycle assessment involving the compilation and quantification of inputs and outputs for a product throughout its life cycle” (ISO 14040:2006, section 3.3).

###Life Cycle Impact Assessment (LCIA)
“Phase of life cycle assessment aimed at understanding and evaluating the magnitude and significance of the potential environmental impacts for a product system throughout the life cycle of the product” (ISO 14040:2006, section 3.4).

###Life cycle interpretation
“Phase of life cycle assessment in which the findings of either the inventory analysis or the impact assessment, or both, are evaluated in relation to the defined goal and scope in order to reach conclusions and recommendations” (ISO 14040:2006, section 3.5).

***

#Impact terms

###Energy Demand
Units: MJ (lower heating value)
A measure of the total amount of primary energy extracted from the earth. PED is expressed in energy demand from non-renewable resources (e.g. petroleum, natural gas, etc.) and energy demand from renewable resources (e.g. hydropower, wind energy, solar, etc.). Efficiencies in energy conversion (e.g. power, heat, steam, etc.) are taken into account. (Guinee, et al., 2002)

###Excess Nutrients
Unit: kg N equivalent
Excess nutrients in the environment, known as eutrophication, covers all potential impacts of excessively high levels of macronutrients, the most important of which are nitrogen (N) and phosphorus (P). Nutrient enrichment may cause an undesirable shift in species composition and elevated biomass production in both aquatic and terrestrial ecosystems. In aquatic ecosystems increased biomass production may lead to depressed oxygen levels, because of the additional consumption of oxygen in biomass decomposition. (Bare, 2011)

###Global Warming Potential
Unit: kg CO2 equivalent
A measure of greenhouse gas emissions, such as CO2 and methane. These emissions are causing an increase in the absorption of radiation emitted by the earth, increasing the natural greenhouse effect. This may in turn have adverse impacts on ecosystem health, human health and material welfare.  Typically the GWP is calculated based on the energy absorption potential of a given greenhouse gas over a 100 year period, though there are other methods which look at different time periods (20 or 300 years).  This version excludes classification of greenhouse gas emissions (and sequestrations) from biogenic sources.  The underlying climate forcing potentials are based on a 100 year period. (Bare, 2011)

###Human Toxicity
Units: CTUh (Potentially Affected Fraction of species.m^3.day/kg emitted)
A measure of toxic emissions that are directly harmful to the health of humans. Human effect factors relate the quantity taken in to the potential risk of cancerous and non-cancerous effects expressing cases per kg of chemical emitted. The final unit is comparative toxic units (CTUh).  The interim factors are estimated with a higher degree of uncertainty than the recommended and should be used with caution. If interim factors are dominating the result of a Life Cycle Assessment a sensitivity analysis should be carried out.  This specific category includes only the recommend characterization factors from the USEtox methodology related to carcinogenic toxic emissions. (Bare, 2011)

###Smog
Units: kg ozone equivalents
A measure of emissions of precursors that contribute to ground level smog formation (mainly ozone O3), produced by the reaction of VOC and carbon monoxide in the presence of nitrogen oxides under the influence of UV light. Ground level ozone may be injurious to human health and ecosystems and may also damage crops. (Bare, 2011)

###Water Consumption
Units: kg of water
A measure of the net intake and release of fresh water across the life of the product system. Blue water refers to surface and ground water only (excluding rain water, green water). Water consumption is typically defined as "water removed from, but not returned to the same drainage basin. Water consumption can be because of evaporation, transpiration, product integration or release into a different drainage basin or the sea. Evaporation from reservoirs is considered water consumption."  This is not an indicator of environmental impact without the addition of information about regional water availability. (thinkstep, 2016)

<br>
<br>

It is critical to note that the impact categories represent potentials—they are approximations of environmental impacts that could occur if emissions would follow a specific impact pathway and meet certain conditions in the receiving environment.  Additionally, the inventory only captures that fraction of the total environmental burden that corresponds to the functional unit (i.e. the relative approach of LCA).  Results are therefore relative expressions only and do not predict actual impacts.  Nor do they measure the exceedance of thresholds, safety margins, hazards, or risks.

DEQ has chosen not to include any weighting or grouping scheme, as this would implicitly require a value-based judgement and is not scientifically based (ISO, 2006).  Each impact is reported separately and thus it is not possible to compare different impact categories to each other. 

***

# Materials

###Cardboard
*Refers to Corrugated Cardboard and Kraft Paper*<p>
Kraft linerboard and container-board cartons of corrugated paper (waxed or
unwaxed) and Kraft paper bags. Excludes converting plant waste paper (i.e.
DLK clippings and local grocery bag waste).

###Carpet
Used carpet fiber, used for housing, seaboard, animal bedding, etc.

###Electronics
Computers (including notebooks and laptops), monitors (CRTs and flat panel) and
televisions (CRTs and flat panel) and other electronic devices, for example cell
phones, printers, VCRs, computer parts.

###Food
Food waste including animal grease and fats.

###Glass
*Refers to Glass Containers*<p>
Glass bottles and jars used to package food, beer, liquor, wine, juice, soft
drinks, medicine, toiletries, and chemicals. Includes bottles that are returned
by consumers to be washed and refilled. Excludes special formula glass,
such as Pyrex glass.

###Trash
*Refers to Nonrecyclables*

###Mixed Paper
A mixture of papers such as unsorted junk mail, telephone directories, and
low-valued grades of paper not listed above, such as chipboard and other
folding boxboard, molded paper containers, envelopes with plastic windows
or pressure-sensitive labels, and paper with thin plastic coatings.

###Newpaper & Magazines
Printed ground-wood newsprint (minimally bleached fiber), newspaper
inserts referred to as #1 news, and magazines. May include magazine type
catalogs. Do not include waste from paper or cardboard mills or large
commercial printing operations. These materials are industrial waste not
post consumer recyclables.

###Plastic Film
Plastic bags, sheeting, and shrink wrap.

###Rigid Plastic
*Refers to Rigid Plastic Containers*<p>
Any container made predominantly of plastic resin that is capable of
maintaining its shape while holding a minimum of eight ounces and a
maximum of five gallons. Excludes film plastic (PF) and plastic products
such as toys (PO).

###Scrap Metal
Appliances (e.g., discarded stoves, washers, dryers, refrigerators, and other
large household appliances or “white goods”) and all other non-industrial
scrap metal.

###Wood
*Refers to Wood/Lumber Waste*<p>
Construction lumber (dimensional lumber construction materials resulting from
remodeling, repair, demolition, or construction of residences, buildings, and other
structures) and packaging lumber used in pallets and crates. Excludes wood waste
from manufacturing (e.g., mobile home manufacturing), wood burned on site for
disposal or used for landfill cover, and branches, logs, etc. from major land
clearing, logging operations, and sawmill operations.

###Yard Debris
Pruning, bulky woody yard waste, leaves, grass clippings, and Christmas trees.